### PR TITLE
fix: assign more restrictive type to PathType (#433)

### LINKED ISSUE #433: datastore.key(['City', undefined]) should be a TypeScript error
#### Environment details

  - OS: Darwin (macOS 10.14.5)
  - Node.js version: v10.15.1
  - npm version: 6.9.0
  - `@google-cloud/datastore` version: 4.0.0

#### Steps to reproduce

  1. Create a key with `undefined` in its path, `datastore.key(['City', undefined])`
  2. Compile and run the code.

Actual result: runtime error:
```
Error: Key path element must not be incomplete: [City: ]
```

Expected result: compile-time error.

### PR DESCRIPTION
**Pull request by growtofill**
This prevents `Key path element must not be incomplete` runtime error, and also allows using big int
(datastore.Int) when creating a key using KeyOptions object as an argument.

Fixes #433 (it's a good idea to open an issue first for discussion)

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by growtofill** [comment]
As a Google TVC, I shouldn't need to sign the CLA explicitly, let me check with my manager.

**Comment by callmehiphop** [comment]
Is this a breaking change for TypeScript users? If so we should update the commit message to indicate that

**Comment by growtofill** [comment]
@callmehiphop yes, in a sense that the code that use to compile may not compile after this update. Is there an example of such message I can use for a reference?

**Comment by JustinBeckwith** [comment]
I think it's fine to call that out in the notes - but I don't think this should be a semver major bump.  This is a "fix" in that it's actually enforcing the types are adequately limited.  Any concerns with including this in a patch release?

**Comment by callmehiphop** [comment]
Applying semver to fix types has always been pretty fuzzy for me, I think in the case of transitioning away from `any` I get a little nervous since it's much more drastic of a change than fixing an incorrect type or adding a missing property. Buuut, if you guys think it's the right way to go, then I say let's go for it! 😎

**Comment by JustinBeckwith** [comment]
@growtofill have you been able to work out the CLA issues?  Would love to merge this!

**Comment by growtofill** [comment]
@JustinBeckwith updated to use private email, sorry for the delay.

**Pull request merged**
