### PR TITLE
feat: support DSInt / DSDouble recognition from JSON

### LINKED ISSUE #59: Key paths are ambiguous, there is no trivial way to serialize a unique entity key!
Hey... So I've read a few issues on this. For example there's  ["Get Unique Entity Key String"](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/625) about "urlsafe" keys. There the apparently accepted solution was to serialize and encode the key path...

However, key paths in nodejs are ambiguous! See [Key IDs Are Coming Back with String Values](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2093).

#### Environment details

  - OS: Ubuntu Linux 16.04
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - @google-cloud/datastore version: 1.3.3

#### Steps to reproduce

```js
const key = db.key(["Post", "31337", "Comment", db.int("999999999999999999")]);
console.log(JSON.stringify(key));
// {"id":"999999999999999999","kind":"Comment","parent":{"name":"31337","kind":"Post","path":["Post","31337"]},"path":["Post","31337","Comment","999999999999999999"]}

const rekey = db.key(key.path);
console.log(JSON.stringify(rekey));
// {"name":"999999999999999999","kind":"Comment","parent":{"name":"31337","kind":"Post","path":["Post","31337"]},"path":["Post","31337","Comment","999999999999999999"]}
```

It's quite clear that any queries relying on the above serialized key path will fail!

I'm not sure if I can just JSON.parse() a key and use it in a query... If yes, that might be a solution, though this serialized format is ridiculously verbose to use as a foreign key or even as a transmission format.

I can work around this by NOT using entity groups AT ALL (cutting out one of the ways I could optimize a Datastore db), and only having references to fixed Kinds (coming from a relational background I can live with this one)... In this case, I can always just store or send a numeric Id (as a decimal string due to JS number limitations). But still, it's kinda painful compared to having a globally unique serializable Id I could easily use for caching, references, etc...

Thanks!

### PR DESCRIPTION
**Pull request by hermanbanken**
We had issues comparable to #59 in the past. IMO the proposed solution in #474 is only half of the solution: the missing part is more forgiving deserialisation. Note also that users like @beaulac [have reported](https://github.com/googleapis/nodejs-datastore/issues/59#issuecomment-366739401) creating work-arounds for this specifically. This PR solves this by extending the constructor of Key.

Fixes #59. Serialization comes with deserialization, and the current
deserialization did not deal well with plain JavaScript objects like
those returned from JSON deserialization.

Given this implementation is it easy & safe to transfers Keys over
networks and other non-JavaScript interfaces.

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by hermanbanken** [comment]
That would be helpful if you transfer entities themselves, but not needed in the case of Keys: or does Google support Keys with Double id's? 😨 

It might be a nice addition for other uses, but I don't want to complicate this PR with that addition.

**Comment by hermanbanken** [comment]
Sure, feel free to add onto this.

I was not considering such API misusage 😇 (`new entity.Key(["User", new Double("3.141592")])`)

**Comment by stephenplusplus** [comment]
@hermanbanken would you please take a look at my changes? According to @googlebot, we'd also need you to confirm you're okay with them as well 👍

**Comment by hermanbanken** [comment]
@googlebot I consent.

**Comment by stephenplusplus** [comment]
Thank you @hermanbanken! Sorry it took me a while to get back to this.

**Pull request merged**
