### PR TITLE
fix: Update the link for the Client API Reference

### PR DESCRIPTION
**Pull request by DominicKramer**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Is there an issue getting these docs on cloud.google.com?

**Comment by DominicKramer** [comment]
@stephenplusplus For me I get a 404 when trying to access the docs through cloud.google.com.

**Comment by stephenplusplus** [comment]
Me too-- @alexander-fenster ?

**Comment by alexander-fenster** [comment]
It's 404 for me as well. I'm OK with the proposed change.

**Comment by stephenplusplus** [comment]
Can we find out what's blocking us from getting on the docs site?

**Comment by alexander-fenster** [comment]
Yes, investigating. I will update the link back when the cloud.google.com section works.

**Pull request merged**
